module.exports = {
  themes:[
    // 'test',
  ],
  components:[
    'dashboard',
    'sampler',
    'documentation',
    'factory',

    'tabs',
    'block-std',
    // 'block-card',
    'btn-load',
    'select2FW',
    'accordionFW',
    'block-editable',
    'ipsum',
    'text-editor',
    'heroFW',
    'sidepanel',
    'datepicker',
    'modalFW',
    'goto',
    // 'konami',
    'input-number',
    'filters',
    'sliderFW',
    'fileUploader',
    // 'priceCard',
    // 'foldingbox',
    // 'headerFW',

    'block-list',
    'block-img',
    'block-flip',

    'table-list',
  ],
  useFA: false, // false || 'free' || 'pro'
  useToastr: true,
  useOutdatebrowser: true,
  useTarteaucitron: true,
  debug: false,
}